//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_semester_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Ingredients
    {
        public int ProductID { get; set; }
        public int IngredientID { get; set; }
        public int Required_ingredient_amount { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Products Products { get; set; }
    }
}
